# The KV260 debug design has no programmable-logic pins exposed at top level.
# Clock and reset are generated by the Zynq UltraScale+ Processing System.
# The PS is configured for a mandatory 200 MHz PL clock in
# create_kv260_debug.tcl. The Zynq PS IP supplies the corresponding 5.000 ns
# clock constraint automatically; duplicating create_clock here would create
# conflicting clock definitions.
#
# Do not add PACKAGE_PIN assignments for the NTT data/control ports: those
# ports are driven and observed through VIO over the on-board JTAG connection.

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
